FROM alpine as builder
RUN apk add --no-cache ca-certificates
USER nobody

FROM alpine
EXPOSE 8443/tcp
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /etc/passwd /etc/passwd
COPY k-rail /k-rail
USER nobody
ENTRYPOINT ["/k-rail", "-config", "/config/config.yml"]