
replicaCount: 3

# Set this to 'Fail' if you wish that resources apply fail if k-rail is unreachable.
failurePolicy: Fail
#reinvocationPolicy: IfNeeded

image:
  repository: cruise/k-rail
  tag:  # left empty for setting override, otherwise uses template default
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Set to the value (in seconds) which the mutatingwebhook should use for a timeout
# for slower clusters (or larger workloads) this may need to be increased
webhookTimeout: 1

config:
  cluster_name: default
  log_level: info
  tls:
    cert: "/cert/cert.pem"
    key: "/cert/key.pem"
  global_report_only: False
  policy_config:
    policy_require_ingress_exemption_classes:
      - public
    policy_trusted_repository_regexes:
      - '^k8s.gcr.io/.*'               # official k8s GCR repo
      - '^[A-Za-z0-9\-:@]+$'           # official docker hub images
    policy_default_seccomp_policy: "runtime/default"
    mutate_empty_dir_size_limit:
      maximum_size_limit: "1Gi"
      default_size_limit: "512Mi"
    mutate_image_pull_policy:
      IfNotPresent: []
      Always: []
    policy_require_service_loadbalancer_annotations:
      - annotation: "cloud.google.com/load-balancer-type"
        allowed_values: 
          - internal
        allow_missing: false
  policies:
    - name: "pod_no_exec"
      enabled: True
      report_only: False
    - name: "pod_no_bind_mounts"
      enabled: True
      report_only: False
    - name: "pod_no_docker_sock"
      enabled: True
      report_only: False
    - name: "pod_immutable_reference"
      enabled: True
      report_only: False
    - name: "pod_no_tiller"
      enabled: True
      report_only: False
    - name: "pod_trusted_repository"
      enabled: True
      report_only: False
    - name: "pod_no_host_network"
      enabled: True
      report_only: False
    - name: "pod_no_privileged_container"
      enabled: True
      report_only: False
    - name: "pod_no_new_capabilities"
      enabled: True
      report_only: False
    - name: "pod_no_host_pid"
      enabled: True
      report_only: False
    - name: "pod_safe_to_evict" # deprecated in favor of pod_mutate_safe_to_evict policy
      enabled: False
      report_only: True
    - name: "pod_mutate_safe_to_evict"
      enabled: True
      report_only: False
    - name: "pod_empty_dir_size_limit"
      enabled: True
      report_only: False
    - name: "pod_default_seccomp_policy"
      enabled: True
      report_only: False
    - name: "pod_no_shareprocessnamespace"
      enabled: True
      report_only: False
    - name: "pod_image_pull_policy"
      enabled: True
      report_only: False
    - name: "ingress_require_ingress_exemption"
      enabled: True
      report_only: False
    - name: "ingress_unique_ingress_host"
      enabled: True
      report_only: False
    - name: "persistent_volume_no_host_path"
      enabled: True
      report_only: False
    - name: "service_require_loadbalancer_exemption"
      enabled: True
      report_only: False
    - name: "cluster_role_binding_no_anonymous_subject"
      enabled: True
      report_only: False
    - name: "role_binding_no_anonymous_subject"
      enabled: True
      report_only: False

exemptions:
  - resource_name: "*"
    namespace: "kube-system"
    username: "*"
    group: "*"
    exempt_policies: ["*"]
