###
# For the Helm deployment, all policy and exemption configuration is contained in deploy/helm/values.yaml.
# This example file is provided for reference.
###

---
# bad-pod needs host network for GCE metadata compromising
- resource_name: bad-pod
  namespace: bad-project
  exempt_policies: ["pod_no_host_network"]

# allow everything
# - resource_name: "*"
#   namespace: "*"
#   username: "*"
#   group: "*"
#   exempt_policies: ["*"]
