apiVersion: v1
kind: PersistentVolume
metadata:
  name: bad-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/data"